console.log('Test console before set interval...');
setInterval(() => {
   console.log('Set interval function executed...');
}, 2000);
console.log('Test console after set interval...');

//Output
/* Test console before set interval...
Test console after set interval...
Set interval function executed...
Set interval function executed...
Set interval function executed... */